name: Publish

on: 
  push:
    tags:
      - 'python-v*.*.*'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: change to ref
        run: git checkout ${{ github.ref_name }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: |
          cd python
          uv python install

      - name: Install the project
        run: |
          cd python
          uv sync --all-extras --dev

      - name: Build the project
        run: |
          cd python
          uv build

      - name: Publish distribution 
        run: |
          cd python
          uv publish

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: ./python/dist/*.tar.gz ./python/dist/*.whl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}' --generate-notes --latest --verify-tag python/dist/**
